=== Bizaarkq/GRUPO13_PARCIAL1/Parcial1-Parte3/registrofacturasgrupo13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="registro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="responsable" type="xs:string"/>
        <xs:element name="factura" type="tipofactura"/>
      </xs:sequence>
      <xs:attribute name="periodo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <!-- Tipo de dato Factura-->  
    <xs:complexType name="tipofactura">
      <xs:sequence>
        <xs:element name="num" type="xs:positiveInteger"/>
        <xs:element name="cliente" type="tipocliente" />
        <xs:element name="direccion" type="tipodir" minOccurs="0"/>
        <xs:element name="lineafactura" type="tipolineaf"/>
        <xs:element name="total" type="tipodinero"/>
      </xs:sequence>
      <xs:attribute name="tipo" type="facturacion" use="required"/>
    </xs:complexType>

    <xs:simpleType name="facturacion">
      <xs:restriction base="xs:string">
        <xs:pattern value="final|credito"></xs:pattern>
      </xs:restriction>
    </xs:simpleType>
  <!-- Fin de tipo dato Factura -->
      
  <!-- Inicio de tipo de dato cliente -->
    <xs:complexType  name="tipocliente">
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="documento" type="tipodocumento"/>
        <!--<xs:choice>
          <xs:group  ref="grupotelefono"/>
        </xs:choice>-->
        <xs:element name="telefonos" type="tipotelefono" minOccurs="0"/>
        <xs:element name="email" type="correo"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="codigo" use="required"/>
      <xs:attribute name="sexo" type="genero" use="required"/>
    </xs:complexType>
    <!--Tipo de dato simple codigo-->
    <xs:simpleType name="codigo">
      <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{3}"></xs:pattern>
      </xs:restriction>
    </xs:simpleType>
    <!--Tipo de dato simple genero-->
    <xs:simpleType name="genero">
      <xs:restriction base="xs:string">
        <xs:enumeration value="masculino"/>
        <xs:enumeration value="femenino"/>
      </xs:restriction>
    </xs:simpleType>

    <!--Tipo de dato complejo dui-->
    <xs:complexType name="tipodocumento">
      <xs:choice>
        <xs:element name="dui">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="tipodui">
                <xs:attribute name="vence" type="xs:date" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="pasaporte">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="tipopasaporte">
                <xs:attribute name="pais" type="xs:string" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
    <!--Tipo dui-->
    <xs:simpleType name="tipodui">
      <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{8}-[0-9]{1}"></xs:pattern>
      </xs:restriction>
    </xs:simpleType>
    <!--Tipo de dato pasaporte-->
    <xs:simpleType name="tipopasaporte">
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{1}[0-9]{8}"></xs:pattern>
      </xs:restriction>
    </xs:simpleType>
    <!--Grupo para tipo de telefono-->
    <xs:group name="grupotelefono">
      <xs:choice>
        <xs:element name="telfcasa">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:pattern value="2[0-9]{7}"/>
              <xs:totalDigits value="8"/>
            </xs:restriction>  
          </xs:simpleType>
        </xs:element>
        <xs:element name="telfcelular" > 
          <xs:complexType >
            <xs:simpleContent>
              <xs:extension base="xs:integer">
                <xs:attribute name="agencia" type="tipoagencia" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="telfofic" type="xs:integer"/>
      </xs:choice>
    </xs:group>
    <!--Tipo de dato telefono-->
    <xs:complexType name="tipotelefono">
      <xs:sequence>
        <xs:group ref="grupotelefono"/>
      </xs:sequence>
    </xs:complexType>

    <!--Tipo de dato agencia-->
    <xs:simpleType name="tipoagencia">
      <xs:restriction base="xs:string">
        <xs:enumeration value="claro"/>
        <xs:enumeration value="movistar"/>
        <xs:enumeration value="digicel"/>
        <xs:enumeration value="tigo"/>
      </xs:restriction>
    </xs:simpleType>
    <!--Tipo de dato correo-->
    <xs:simpleType name="correo">
        <xs:restriction base="xs:string">
          <xs:pattern value="([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
  <!-- Fin de tipo de dato cliente -->




  <!-- Tipo de dato Direccion-->
    <xs:complexType name="tipodir">
      <xs:choice>
        <xs:element name="oficina" type="xs:string"/>
        <xs:element name="casa" type="xs:string"/>
      </xs:choice>
      <xs:attribute name="depto" type="tipodepto"/>
      <xs:attribute name="municipio" type="tipomuni"/>
    </xs:complexType>

    <xs:simpleType name="tipodepto">
      <xs:restriction base="xs:string">
        <xs:enumeration value="San Salvador"/>
        <xs:enumeration value="La Libertad"/>
        <xs:enumeration value="Sonsonate"/>
        <xs:enumeration value="Ahuachapán"/>
        <xs:enumeration value="Chalatenango"/>
        <xs:enumeration value="Santa Ana"/>
        <xs:enumeration value="La Paz"/>
        <xs:enumeration value="Cabañas"/>
        <xs:enumeration value="San Miguel"/>
        <xs:enumeration value="Usulután"/>
        <xs:enumeration value="Morazán"/>
        <xs:enumeration value="San Vicente"/>
        <xs:enumeration value="La Unión"/>
        <xs:enumeration value="Cuscatlán"/>
      </xs:restriction>
    </xs:simpleType>
      
    <xs:simpleType name="tipomuni">
      <xs:restriction base="xs:string">
        <xs:minLength value="5"/>
        <xs:maxLength value="25"/>
      </xs:restriction>
    </xs:simpleType>
  <!-- Fin de Tipo de dato Direccion--> 
  
  <!-- Tipo de dato Linea Factura-->
    <xs:complexType name="tipolineaf">
      <xs:sequence>
        <xs:element name="codigo">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="tipocodigofactura">
                <xs:attribute name="tipo" type="tipocarac" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="detalle" type="xs:string"/>
        <xs:element name="cantidad" type="xs:positiveInteger"/>
        <xs:element name="precio" type="tipodinero"/>
        <xs:element name="subtotal" type="tipodinero"/>
      </xs:sequence>
      <xs:attribute name="factura" type="xs:positiveInteger"/>
    </xs:complexType>
    
    <xs:simpleType name="tipocodigofactura">
      <xs:restriction base="xs:positiveInteger">
        <xs:maxInclusive value="9999"/>
      </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipocarac">
      <xs:restriction base="xs:string">
        <xs:enumeration value="souvenir"/>
        <xs:enumeration value="accesorio_pc"/>
        <xs:enumeration value="pcportatiles"/>
        <xs:enumeration value="perecedero"/>
        <xs:enumeration value="pcescritorio"/>
        <xs:enumeration value="monitores"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="tipodinero">
      <xs:sequence>
        <xs:element name="moneda">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="$"/>
              <xs:enumeration value="£"/>
              <xs:enumeration value="BTC"/>
              <xs:enumeration value="€"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="valor">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="0.01"/>
              <xs:fractionDigits value="2"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  <!-- Fin de Tipo de dato Linea Factura-->

</xs:schema>

=== Bizaarkq/GRUPO13_PARCIAL1/Parcial1-Parte3/registro_facturas_grupo13.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- grupo 13 -->
<registro periodo="2012-03" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="registrofacturasgrupo13.xsd">
  <responsable>Lic. Inocencio Pérez</responsable>
  
  <factura tipo="final">
    <num>564</num>
    <cliente codigo="001" sexo="femenino">
      <nombre>María Vélez</nombre>
      <documento>
        <dui vence="2018-03-03">02349867-9</dui>
      </documento>
      <telefonos>
        <telfcasa >22252222</telfcasa>
      </telefonos>
      <email>mariav@gmail.com</email>
    </cliente>
    <direccion depto="San Salvador" municipio="San Salvador">
      <casa>Prados del Bosque Num.23</casa>
    </direccion>
    <lineafactura factura="564">
      <codigo tipo="souvenir">498</codigo>
      <detalle>Llavero estampas de mi pueblo: Izalco</detalle>
      <cantidad>10</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>1.13</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>11.30</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>11.30</valor>
    </total>
  </factura>
  
  <factura tipo="credito">
    <num>570</num>
    <cliente codigo="002" sexo="femenino">
      <nombre>Julia Pérez</nombre>
      <documento>
        <pasaporte pais="USA">A98672340</pasaporte>
      </documento>
      <telefonos>
        <telfcelular agencia="movistar">78757471</telfcelular>
      </telefonos>
      <email>jperez@sica.com</email>
    </cliente>
    <direccion depto="La Libertad" municipio="Antiguo Cuscatlan">
      <oficina>5 Av. Sur</oficina>
    </direccion>
    <lineafactura factura="570">
      <codigo tipo="pcportatiles">734</codigo>
      <detalle>netbook acer a240</detalle>
      <cantidad>3</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>350.00</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>1050.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>1050.00</valor>
    </total>
  </factura>
  
  <factura tipo="credito">
    <num>575</num>
    <cliente codigo="003" sexo="masculino">
      <nombre>Jhon Smith</nombre>
      <documento>
        <pasaporte pais="USA">A98670234</pasaporte>
      </documento>
      <telefonos>
        <telfcasa>21202222</telfcasa>
      </telefonos>
    <email>jsmith@usaid.com</email>
    </cliente>
    <direccion depto="La Libertad" municipio="Santa Tecla">
      <oficina>Final 25 Av. Norte</oficina>
    </direccion>
    <lineafactura factura="575">
      <codigo tipo="accesorio_pc">247</codigo>
      <detalle>Mouse inalámbrico</detalle>
      <cantidad>5</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>10.00</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>50.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>50.00</valor>
    </total>
  </factura>
  
  <factura tipo="final">
    <num>590</num>
    <cliente codigo="004" sexo="masculino">
      <nombre>Juan Pérez</nombre>
      <documento>
        <pasaporte pais="SLV">A40298367</pasaporte>
      </documento>
      <telefonos>
        <telfcasa >20212223</telfcasa>
      </telefonos>
      <email>jperez@gmail.com</email>
    </cliente>
    <lineafactura factura="590">
      <codigo tipo="perecedero">213</codigo>
      <detalle>Agua embotellada</detalle>
      <cantidad>10</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>0.50</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>5.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>5.00</valor>
    </total>
  </factura>
  
  <factura tipo="final">
    <num>593</num>
    <cliente codigo="005" sexo="masculino">
      <nombre>Pedro Portillo</nombre>
      <documento>
       <pasaporte pais="SLV">A43698027</pasaporte>
      </documento>
      <telefonos>
        <telfcasa >24252627</telfcasa>
      </telefonos>
      <email>pportillo@hotmail.com</email>
    </cliente>
    <lineafactura factura="593">
      <codigo tipo="perecedero">215</codigo>
      <detalle>Soda enlatada</detalle>
      <cantidad>24</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>0.50</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>5.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>5.00</valor>
    </total>
  </factura>
  
  <factura tipo="credito">
    <num>585</num>
    <cliente codigo="006" sexo="masculino">
      <nombre>Jhon Smith</nombre>
      <documento>
        <dui vence="2018-06-03">02810867-0</dui>
      </documento>
      <telefonos>
        <telfcasa >25262728</telfcasa>
      </telefonos>
      <email>jsmith@usaid.com</email>
    </cliente>
    <direccion depto="La Libertad" municipio="Santa Tecla">
      <oficina>Final 25 Av. Norte</oficina>
    </direccion>
    <lineafactura factura="575">
      <codigo tipo="accesorio_pc">247</codigo>
      <detalle>Mouse inalámbrico</detalle>
      <cantidad>10</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>10.00</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>100.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>100.00</valor>
    </total>
  </factura>
  
  <factura tipo="final">
    <num>501</num>
    <cliente codigo="007" sexo="femenino">
      <nombre>Marta Alicia</nombre>
      <documento>
        <pasaporte pais="SLV">B40292519</pasaporte>
      </documento>
      <telefonos>
        <telfcelular agencia="tigo">71757471</telfcelular>
      </telefonos>
      <email>marticia@yahoo.com</email>
    </cliente>
    <direccion depto="Ahuachapán" municipio="Apaneca">
      <oficina>Av. 15 de Abril Norte</oficina>
    </direccion>
    <lineafactura factura="501">
      <codigo tipo="perecedero">319</codigo>
      <detalle>Pastelito de chocolate</detalle>
      <cantidad>5</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>0.35</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>1.75</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>1.75</valor>
    </total>
  </factura>

  <factura tipo="final">
    <num>469</num>
    <cliente codigo="008" sexo="masculino">
      <nombre>Marco Florencio</nombre>
      <documento>
        <dui vence="2028-09-13">02813717-0</dui>
      </documento>
      <telefonos>
        <telfcelular agencia="claro">79754471</telfcelular>
      </telefonos>
      <email>mflowren@outlook.com</email>
    </cliente>
    <lineafactura factura="469">
      <codigo tipo="pcescritorio">798</codigo>
      <detalle>Lenovo m700sff</detalle>
      <cantidad>3</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>400.00</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>1200.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>1200.00</valor>
    </total>
  </factura>

  <factura tipo="credito">
    <num>618</num>
    <cliente codigo="009" sexo="masculino">
      <nombre>Samuel Herrón</nombre>
      <documento>
        <pasaporte pais="USA">U99125581</pasaporte>
      </documento>
      <telefonos>
        <telfcelular agencia="movistar">61757471</telfcelular>
      </telefonos>
      <email>serronel@oracle.com</email>
    </cliente>
    <direccion depto="Chalatenango" municipio="Agua Caliente">
      <oficina>Calle Tránsito Aguilar</oficina>
    </direccion>
    <lineafactura factura="618">
      <codigo tipo="monitores">988</codigo>
      <detalle>ASUS TUF Gaming VG32AQL1A</detalle>
      <cantidad>1</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>500.00</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>500.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>500.00</valor>
    </total>
  </factura>

  <factura tipo="credito">
    <num>672</num>
    <cliente codigo="100" sexo="femenino">
      <nombre>Maria Mendoza</nombre>
      <documento>
        <dui vence="2030-12-29">15582763-6</dui>
      </documento>
      <telefonos>
        <telfcelular agencia="digicel">73217471</telfcelular>
      </telefonos>
      <email>maridoza@outlook.com</email>
    </cliente>
    <lineafactura factura="672">
      <codigo tipo="accesorio_pc">165</codigo>
      <detalle>Audifonos SONY</detalle>
      <cantidad>2</cantidad>
      <precio>
        <moneda>$</moneda>
        <valor>25.00</valor>
      </precio>
      <subtotal>
        <moneda>$</moneda>
        <valor>50.00</valor>
      </subtotal>
    </lineafactura>
    <total>
      <moneda>$</moneda>
      <valor>50.00</valor>
    </total>
  </factura>
</registro>
